#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0) uniform samplerCube hdrCubeMap;

layout(binding = 1) uniform writeonly imageCube preFilteredMap;

layout(push_constant) uniform constants{
    float roughness;
} PushConstant;
const float PI = 3.14159265359;

vec3 GetCubeMapDirection(vec2 uv, int faceIndex)
{
    float u = uv.x * 2.0 - 1.0;
    float v = uv.y * 2.0 - 1.0;
    
    switch(faceIndex) {
        case 0: return vec3(1.0,  -v, -u); // +X (Right)
        case 1: return vec3(-1.0, -v,  u); // -X (Left)
        case 2: return vec3(u, 1.0, v);    // +Y (Top)
        case 3: return vec3(u, -1.0, -v);  // -Y (Bottom)
        case 4: return vec3(u,  -v, 1.0);  // +Z (Front)
        case 5: return vec3(-u, -v, -1.0); // -Z (Back)
    }
    return vec3(0.0);
}

float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float a      = roughness*roughness;
    float a2     = a*a;
    float NdotH  = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;
	
    float num   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom + 0.001;
	
    return num / denom;
}

float RadicalInverse_VdC(uint bits) 
{
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10; // / 0x100000000
}

// ----------------------------------------------------------------------------
vec2 Hammersley(uint i, uint N)
{
    return vec2(float(i)/float(N), RadicalInverse_VdC(i));
}

vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float roughness)
{
    float a = roughness*roughness;
	
    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);
	
    // from spherical coordinates to cartesian coordinates
    vec3 H;
    H.x = cos(phi) * sinTheta;
    H.y = sin(phi) * sinTheta;
    H.z = cosTheta;
	
    // from tangent-space vector to world-space sample vector
    vec3 up        = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent   = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);
	
    vec3 sampleVec = tangent * H.x + bitangent * H.y + N * H.z;
    return normalize(sampleVec);
}  

void main()
{		
    ivec2 pixelPos = ivec2(gl_GlobalInvocationID.xy);
    int face = int(gl_GlobalInvocationID.z);
    
    // Get the size of the face
    ivec2 size = imageSize(preFilteredMap);
    
    if (pixelPos.x >= size.x || pixelPos.y >= size.y) return;

    vec2 uv = (vec2(pixelPos) + 0.5) / vec2(size);
    
    vec3 N = normalize(GetCubeMapDirection(uv, face));
    vec3 R = N;
    vec3 V = R;
    if (PushConstant.roughness == 0.0) {
        // No convolution needed, just copy the pixel
        vec3 color = texture(hdrCubeMap, R).rgb;
        imageStore(preFilteredMap, ivec3(pixelPos, face), vec4(color, 1.0));
        return;
    }
    

    const uint SAMPLE_COUNT = 4096u;
    float totalWeight = 0.0;   
    vec3 prefilteredColor = vec3(0.0);     
    for(uint i = 0u; i < SAMPLE_COUNT; ++i)
    {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H  = ImportanceSampleGGX(Xi, N, PushConstant.roughness);
        vec3 L  = normalize(2.0 * dot(V, H) * H - V);

        float NdotL = max(dot(N, L), 0.0);
        if(NdotL > 0.0)
        {
            float D = DistributionGGX(N, H, PushConstant.roughness);
            float NdotH = max(dot(N, H), 0.0);
            float HdotV = max(dot(H, V), 0.0);
            float pdf = D * NdotH / (4.0 * HdotV) + 0.0001;
            float resolution = 1024.0;
            float saTexel  = 4.0 * PI / (6.0 * resolution * resolution);
            float saSample = 1.0 / (float(SAMPLE_COUNT) * pdf + 0.0001);

            float mipLevel = PushConstant.roughness == 0.0 ? 0.0 : 0.5 * log2(saSample / saTexel);
            prefilteredColor += min(textureLod(hdrCubeMap, L, mipLevel).rgb, vec3(1000.0)) * NdotL;
            // prefilteredColor += textureLod(hdrCubeMap, L, mipLevel).rgb * NdotL;
            totalWeight += NdotL;
        }
    }
    prefilteredColor = prefilteredColor / max(totalWeight, 0.001);

    imageStore(preFilteredMap, ivec3(pixelPos, face), vec4(prefilteredColor, 1.0));
}  
